### ISSUE TITLE
Incompatibility with Ghidra 11.1.1

### ISSUE THREAD

**Issue by v-p-b** [nccgroup/Cartographer#11]
**Describe the bug**
Ghidra [removed](https://scrapco.de/ghidra_docs/javadoc/ghidra/app/plugin/PluginCategoryNames.html) `PluginCategoryNames.DECOMPILER` at some point, so the project won't build with the latest Ghidra version linked. 

**To Reproduce**
1. set `GHIDRA_INSTALL_DIR` to the path of your Ghidra 11.1.1 installation
2. run `gradle build`
3. Observe 
4. See error:

```
/path/to/Cartographer/src/main/java/cartographer/CartographerPlugin.java:70: error: cannot find symbol
    category = PluginCategoryNames.DECOMPILER,
```

**Expected behavior**
The project builds with latest Ghidra

**Screenshots**
N/A

**Additional context**
You should just choose an appropriate alternative category, with that the project builds.

**Comment by TheZ3ro** [comment]
#8, #9 and #10 both fix this issue

**Comment by v-p-b** [comment]
> #8, #9 and #10 all fix this issue

Thanks, I missed those but they seem quite useful to base my further work on!
